### ISSUE TITLE
Can you upload Kitty annotation?

### ISSUE THREAD

**Issue by childult-programmer** [imatif17/Prototype-Mean-Teacher#9]
Can you upload kitty annotation via google drive?

**Comment by imatif17** [comment]
I don't think I'm allowed to do that because of copyright issues.

**Comment by childult-programmer** [comment]
ohoh then, can you uploda just some example cia capture (like just 000000.xml)

Because i download annotation on the kitty page, and convert it to xml format, but when i load it, it shows int/float error. I want to compare it with yout examples!

Thank you for youre insigtful researches

**Comment by imatif17** [comment]
I have uploaded an example.

And, I used their code (with some modification) to convert the dataset [https://github.com/umautobots/vod-converter](https://github.com/umautobots/vod-converter) 

[000.pdf](https://github.com/user-attachments/files/16883495/000.pdf)

**Comment by childult-programmer** [comment]
Thank you so much!
